#!/bin/bash

echo "=> install manifest-tool"
URL=https://github.com/estesp/manifest-tool/releases/download/v0.3.0/manifest-tool-amd64-linux

curl -sLo ./manifest-tool ${URL}
chmod +x ./manifest-tool


echo "=> push multiarch"

VERSION="3.5"
ARCH="linux/arm,linux/amd64"

./manifest-tool push from-args \
--platforms ${ARCH} \
--template ${DOCKER_REPO}:ARCH-${VERSION} \
--target ${DOCKER_REPO}:${VERSION}

:<<EOM
echo "=> push multiarch"
./manifest-tool push from-spec manifest.yml
EOM
