#!/bin/bash

# tag and push correct image names

echo "=> tag image"
docker tag alpine:3.5 firecyberice/alpine:amd64-3.5
docker tag alpine-armhf:3.5 firecyberice/alpine:arm-3.5

echo "=> push image"
docker push firecyberice/alpine:amd64-3.5
docker push firecyberice/alpine:arm-3.5

